name: Security

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    name: Vulnerability scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Cache FHIR Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.fhir/packages
          key: fhir-packages

      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run vulnerability scan
        uses: snyk/actions/gradle-jdk16@master
        continue-on-error: true # enable for SARIF to upload properly
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --all-sub-projects --configuration-matching='^runtimeClasspath'
          command: test

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
